behaviors:
  MirrorMode:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 0.5
        gamma: 0.99
      gail:
        gamma: 0.9
        strength: 1.0
        network_settings:
          normalize: true
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.0001
        encoding_size: null
        use_actions: true
        use_vail: false
        demo_path: C:\Users\Yanna\Documents\GitHub\MirrorMode\FireEmblemEnvironment\Assets\Demonstrations
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 2000
    threaded: false
    self_play: null
    behavioral_cloning:
      demo_path: C:\Users\Yanna\Documents\GitHub\MirrorMode\FireEmblemEnvironment\Assets\Demonstrations
      steps: 900000
      strength: 0.4
      samples_per_update: 10
      num_epoch: null
      batch_size: 512
